// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.1.8",
  "ch.qos.logback" % "logback-core" % "1.1.8",
  "com.chuusai" % "shapeless_2.11" % "2.3.2",
  "com.github.melrief" % "pureconfig_2.11" % "0.5.1",
  "com.github.mpilquist" % "simulacrum_2.11" % "0.8.0",
  "com.typesafe" % "config" % "1.3.1",
  "io.monix" % "monix-eval_2.11" % "2.0.5",
  "io.monix" % "monix-execution_2.11" % "2.0.5",
  "io.monix" % "monix-reactive_2.11" % "2.0.5",
  "io.monix" % "monix-types_2.11" % "2.0.5",
  "io.monix" % "monix_2.11" % "2.0.5",
  "joda-time" % "joda-time" % "2.9.4",
  "org.joda" % "joda-convert" % "1.8.1",
  "org.reactivestreams" % "reactive-streams" % "1.0.0",
  "org.scala-sbt" % "test-interface" % "1.0",
  "org.scalacheck" % "scalacheck_2.11" % "1.12.5",
  "org.slf4j" % "slf4j-api" % "1.7.21",
  "org.typelevel" % "catalysts-macros_2.11" % "0.0.2",
  "org.typelevel" % "catalysts-platform_2.11" % "0.0.2",
  "org.typelevel" % "cats-core_2.11" % "0.7.2",
  "org.typelevel" % "cats-free_2.11" % "0.7.2",
  "org.typelevel" % "cats-jvm_2.11" % "0.7.2",
  "org.typelevel" % "cats-kernel-laws_2.11" % "0.7.2",
  "org.typelevel" % "cats-kernel_2.11" % "0.7.2",
  "org.typelevel" % "cats-laws_2.11" % "0.7.2",
  "org.typelevel" % "cats-macros_2.11" % "0.7.2",
  "org.typelevel" % "cats_2.11" % "0.7.2",
  "org.typelevel" % "discipline_2.11" % "0.4",
  "org.typelevel" % "machinist_2.11" % "0.4.1",
  "org.typelevel" % "macro-compat_2.11" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH f7ab32671fa83f6976aaee384771b4b087d3023e
